### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by DanielPlainview** [tcz/phpunit-mockfunction#3]
Any chance to see release of this project? My religion blames me for "dev-master" in the dependencies.

**Comment by tcz** [comment]
Thanks! For the stable release I felt I needed to add continuous integration. I added Travis-CI (see on home) and tagged v1.0.0

**Comment by DanielPlainview** [comment]
Thanks!

**Comment by DanielPlainview** [comment]
Ah, and could you please update https://packagist.org/packages/tcz/phpunit-mockfunction? Packagist still doesn't know about this release.

**Comment by tcz** [comment]
I can see it there, I guess it just needed to update:

![image](https://f.cloud.github.com/assets/160008/2484054/563059d6-b108-11e3-999d-941eb8fa26c0.png)
