### ISSUE TITLE
Question about using mockfunction without a scope object

### ISSUE THREAD

**Issue by davetbo** [tcz/phpunit-mockfunction#7]
Hello,

I'm trying to test a WP Plugin.  I'm currently trying to mock a get_option call that is being called from my functions.php file, so it's not being called from within an object.  

I've already successfully used mockfunction for mocking core WP functions which are called from within an object, so I know I've got mockfunction working generally.  However, I'm not sure how to mock these functions when they're called from outside of an object context.  

Any advice?  I really appreciate your help, and your great phpunit plugin!

**Comment by tcz** [comment]
You can try passing `null` as the scope and then call the `restore` method when your test ends.
This is a bit messy because it might affect other parts of the code as well, but it might work for you.

**Comment by davetbo** [comment]
Thanks! I will give that a try.
